# docker-compose up --build -> construirea celor doua api-uri
# docker-compose down -> oprirea si curatarea celor doua api-uri
version: "3.8"

services:
  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./ProductService/.env

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./OrderService/.env
